spring.application.name=enterpriseapp

# H2 DATABASE
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf
spring.thymeleaf.cache=false
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587

spring.mail.username=d0a35540bf0951
spring.mail.password=Rsca4ever1233@

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.ssl.trust=sandbox.smtp.mailtrap.io
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false

spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2